services:
  api:
    build:
      context: ./api 
    container_name: api_ia
    ports:
      - "8001:8001"  
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres_api
    networks:
      - data_network

networks:
  data_network:
    driver: bridge
    external: true

volumes:
  pg_data: